models/vacinador.py
import re

from extensions import db


class Vacinador(db.Model):
    crm = db.Column(db.String(15), primary_key=True)
    cpf = db.Column(db.String(12), nullable=False, unique=True)
    nome = db.Column(db.String(128), nullable=False)
    dtNascimento = db.Column(db.Date, nullable=False)
    aplicacao = db.relationship('Aplicacao', backref='vacinador', cascade="all, delete", passive_deletes=False, lazy=True)

    @staticmethod
    def trazer_crm(param):
        txt = re.search("([A-Z|a-z]{3})([A-Z|a-z]{2})([0-9]{6})", param)
        txt = f"{txt.group(1)}/{txt.group(2)} {txt.group(3)}"
        return txt.upper()

    @staticmethod
    def add_crm_banco(param: str) -> str:
        param = param.upper()
        param = re.sub(r"\s+", "", param)
        crm = re.search("([A-Z]{3})(/)([A-Z]{2})([0-9]{6})", param)
        crm = crm.group(1) + crm.group(3) + crm.group(4)
        return crm.upper()

routes/vacinador_route.py
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for

from extensions import db
from models.vacinador import Vacinador

vacinador_route = Blueprint('vacinador_route', __name__)


@vacinador_route.route('/vacinador')
def vacinador():
    lista = Vacinador.query.all()
    for vacinador in lista:
        vacinador.crmtemplate = Vacinador.trazer_crm(vacinador.crm)
    return render_template('vacinador/vacinador_lista.html', titulo="Lista de vacinadores", vacinadores=lista)


@vacinador_route.route('/vacinador/novo')
def vacinador_novo():
    return render_template("vacinador/vacinador_novo.html", titulo="Novo vacinador")


@vacinador_route.route('/vacinador/criar', methods=['POST', ])
def vacinador_criar():
    nome = request.form['nome']
    cpf = request.form['cpf']
    crm = Vacinador.add_crm_banco(request.form['crm'])
    dt_nascimento = datetime.strptime(request.form['nascimento'], '%Y-%m-%d').date()

    vacinador = Vacinador(nome=nome, cpf=cpf, crm=crm, dtNascimento=dt_nascimento)
    db.session.add(vacinador)
    db.session.commit()
    return redirect(url_for('vacinador_route.vacinador'))


@vacinador_route.route('/vacinador/atualizar/<string:crm>', methods=['POST', ])
def vacinador_atualizar(crm):
    vacinador = Vacinador.querry.filter_by(crm=crm).first()
    if vacinador:
        vacinador.nome = request.form['nome']
        vacinador.cpf = request.form['cpf']
        vacinador.dt_nascimento = datetime.strptime(request.form['nascimento'], '%Y-%m-%d').date()
        db.session.commit()
    return redirect(url_for('vacinador_route.vacinador'))


@vacinador_route.route('/vacinador/editar/<string:crm>')
def vacinador_editar(crm):
    vacinador = Vacinador.query.filter_by(crm=crm).first()
    return render_template("vacinador/vacinador_editar.html", titulo="Editando Vacinador", vacinador=vacinador)


@vacinador_route.route('/vacinador/excluir/<string:crm>', methods=['DELETE', 'GET'])
def vacinador_excluir(crm):
    vacinador = Vacinador.query.filter_by(crm=crm).first()
    db.session.delete(vacinador)
    db.session.commit()
    return redirect(url_for('vacinador_route.vacinador'))

routes/vacinaroute.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from Test.vacinaTest import VacinaTest
from extensions import db
from models.vacina import Vacina

vacinaroute = Blueprint('vacinaroute', __name__)


@vacinaroute.route('/')
def index():
    return render_template('index.html')


@vacinaroute.route('/vacina/')
def vacina():
    vacinas = Vacina.query.all()
    return render_template('vacina/vacina_lista.html', titulo="Vacinas", vacinas=vacinas)


@vacinaroute.route('/vacina/novo/')
def vacina_novo():
    return render_template("vacina/vacina_novo.html", titulo="Nova Vacina")


@vacinaroute.route('/vacina/criar', methods=['POST', ])
def vacina_criar():
    nome = request.form['nome']
    vacinaTest = VacinaTest(nome=nome)
    if vacinaTest.value:
        vacina = Vacina(nome=vacinaTest.text)
        db.session.add(vacina)
        db.session.commit()
        return redirect(url_for('vacinaroute.vacina'))
    else:
        flash(str(vacinaTest.text), 'alert-danger')
        return redirect(url_for('vacinaroute.vacina_novo'))


@vacinaroute.route('/vacina/editar/<id>')
def vacina_editar(id):
    vacina = Vacina.query.filter_by(id=id).first()
    return render_template('vacina/vacina_editar.html', vacina=vacina)


@vacinaroute.route('/vacina/atualizar/<id>', methods=['POST'])
def vacina_atualizar(id):
    nome = request.form['nome']
    vacina = Vacina.query.filter_by(id=id).first()
    vacina.nome = nome
    db.session.commit()
    return redirect(url_for("vacinaroute.vacina"))


@vacinaroute.route('/vacina/excluir/<int:id>', methods=['DELETE', 'GET'])
def vacina_excluir(id):
    vacina = Vacina.query.filter_by(id=id).first()
    db.session.delete(vacina)
    db.session.commit()
    return redirect(url_for('vacinaroute.vacina'))

templates/vacinador/vacinador_editar.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('vacinador_route.vacinador_atualizar', crm=vacinador.crm) }}" method="post" class="needs-validation" novalidate>
    <fieldset>
        <div class="form-group has-validation">
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control" value="{{vacinador.nome}}" required>
            <div class="invalid-feedback">
                Insira um Nome.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="cpf">CPF</label>
            <input type="text" id="cpf" name="cpf" class="form-control" value="{{vacinador.cpf}}" required>
            <div class="invalid-feedback">
                Insira um CPF.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="nascimento">Data de Nascimento</label>
            <input type="date" id="nascimento" name="nascimento" class="form-control" value="{{vacinador.dtNascimento}}"
                required>
            <div class="invalid-feedback">
                Insira sua data de nascimento.
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-salvar">Salvar</button>
        <a class="btn btn-danger" href="{{url_for('vacinador_route.vacinador')}}">Cancelar</a>
    </fieldset>
</form>
{% include "script.html"%}
{% endblock %}

templates/vacinador/vacinador_lista.html
{% extends "templates.html" %}
{% block conteudo %}
<table class="table table-striped table-responsive table-bordered">
    <thead class="thead-default">
    <tr>
        <th>Nome</th>
        <th>Nascimento</th>
        <th>CPF</th>
        <th>CRM</th>
        <th>Data de Nascimento</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for vacinador in vacinadores %}
    <tr>
        <td>{{ vacinador.nome }}</td>
        <td>{{ vacinador.dtNascimento.strftime('%d/%m/%Y') }}</td>
        <td>{{ vacinador.cpf }}</td>
        <td>{{ vacinador.crmtemplate }}</td>
        <td>{{ vacinador.dtNascimento.strftime('%d/%m/%Y') }}</td>
        <td>
            <a href="{{ url_for('vacinador_route.vacinador_editar', crm= vacinador.crm) }}" class="btn btn-warning">editar</a>
            <a href="{{ url_for('vacinador_route.vacinador_excluir', crm= vacinador.crm) }}" class="btn btn-danger">excluir</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    <a href="{{url_for('vacinador_route.vacinador_novo')}}" class="btn btn-primary">Cadastrar</a>
    <a href="{{url_for('vacinaroute.index')}}" class="btn btn-dark">Voltar</a>
{% endblock %}

templates/vacinador/vacinador_novo.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('vacinador_route.vacinador_criar') }}" method="post" class="needs-validation" novalidate>
    <fieldset>
        <div class="form-group has-validation">
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control" required>
            <div class="invalid-feedback">
                Insira um Nome.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="cpf">CPF</label>
            <input type="text" id="cpf" name="cpf" class="form-control" required>
            <div class="invalid-feedback">
                Insira um CPF.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="crm">CRM</label>
            <input type="text" id="crm" name="crm" class="form-control" required>
            <div class="invalid-feedback">
                Insira um CRM.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="nascimento">Data de Nascimento</label>
            <input type="date" id="nascimento" name="nascimento" class="form-control" required>
            <div class="invalid-feedback">
                Insira sua data de nascimento.
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-salvar">Salvar</button>
        <a class="btn btn-danger" href="{{url_for('vacinador_route.vacinador')}}">Cancelar</a>
    </fieldset>
</form>
{% include "script.html"%}
{% endblock %}