models/aplicacao.py
from extensions import db


class Aplicacao(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    crm = db.Column(db.String(15), db.ForeignKey('vacinador.crm', ondelete="CASCADE"), nullable=False)
    cns = db.Column(db.String(15), db.ForeignKey('vacinado.cns', ondelete="CASCADE"), nullable=False)
    id_vacina = db.Column(db.Integer, db.ForeignKey('vacina.id', ondelete="CASCADE"), nullable=False)
    data = db.Column(db.Date, nullable=False)

routes/aplicacao_route.py
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for

from extensions import db
from models.aplicacao import Aplicacao
from models.vacina import Vacina
from models.vacinado import Vacinado
from models.vacinador import Vacinador

aplicacaoroute = Blueprint('aplicacaoroute', __name__)


@aplicacaoroute.route('/aplicacao/')
def aplicacao():
    lista = Aplicacao.query.all()
    return render_template('aplicacao/aplicacao_list.html', titulo='Aplicações de Vacinas', aplicacoes=lista)


@aplicacaoroute.route('/aplicacao/novo/')
def aplicacao_novo():
    lista_vacina = Vacina.query.all()
    lista_vacinador = Vacinador.query.all()
    lista_vacinado = Vacinado.query.all()

    for vacinador in lista_vacinador:
        vacinador.crmtemplate = Vacinador.trazer_crm(vacinador.crm)

    return render_template("aplicacao/aplicacao_novo.html", titulo="Nova Aplicacao.", vacinas=lista_vacina,
                           vacinadores=lista_vacinador, vacinados=lista_vacinado)


@aplicacaoroute.route('/aplicacao/criar', methods=['POST', ])
def aplicacao_criar():
    id_vacina = request.form['vacina']
    cns = request.form['vacinado']
    crm = request.form['vacinador']
    data = datetime.now().date()
    aplicacao = Aplicacao(id_vacina=id_vacina, cns=cns, crm=crm, data=data)

    db.session.add(aplicacao)
    db.session.commit()
    att_dose(aplicacao.cns)

    return redirect(url_for('aplicacaoroute.aplicacao'))


@aplicacaoroute.route('/aplicacao/editar/<int:id>')
def aplicacao_editar(id):
    aplicacao = Aplicacao.query.filter_by(id=id).first()
    lista_vacina = Vacina.query.all()
    lista_vacinador = Vacinador.query.all()
    lista_vacinado = Vacinado.query.all()

    for vacinador in lista_vacinador:
        vacinador.crmtemplate = Vacinador.trazer_crm(vacinador.crm)

    return render_template("aplicacao/aplicacao_editar.html", aplicacao=aplicacao, vacinados=lista_vacinado,
                           vacinadores=lista_vacinador, vacinas=lista_vacina)


@aplicacaoroute.route('/aplicacao/atualizar/<int:id>', methods=['POST', ])
def aplicacao_atualizar(id):
    aplicacao = Aplicacao.query.filter_by(id=id)
    aplicacao.id_vacina = request.form['vacina']
    aplicacao.cns = request.form['vacinado']
    aplicacao.crm = request.form['vacinador']
    db.session.commit()
    att_dose(aplicacao.cns)
    return redirect(url_for("aplicacaoroute.aplicacao"))


@aplicacaoroute.route('/aplicacao/excluir/<int:id>', methods=['GET', 'DELETE'])
def aplicacao_excluir(id):
    aplicacao = Aplicacao.query.filter_by(id=id).first()
    cns = aplicacao.cns
    db.session.delete(aplicacao)
    db.session.commit()
    if cns:
        att_dose(cns)
    return redirect(url_for('aplicacaoroute.aplicacao'))


@aplicacaoroute.route('/aplicacao/filtro/', methods=['POST', ])
def aplicacao_filtro():
    cpf = request.form['cpf']
    lista = Aplicacao.query.join(Vacinado).where(Vacinado.cpf == cpf)
    if lista:
        return render_template('aplicacao/aplicacao_list.html', titulo='Aplicações de Vacinas', aplicacoes=lista)
    else:
        return redirect(url_for('aplicacaoroute.aplicacao'))


def att_dose(cns):
    qtd = Aplicacao.query.where(Aplicacao.cns == cns).count()
    vacinado = Vacinado.query.filter_by(cns=cns).first()
    vacinado.qtdDose = qtd
    db.session.commit()

routes/vacinaroute.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from Test.vacinaTest import VacinaTest
from extensions import db
from models.vacina import Vacina

vacinaroute = Blueprint('vacinaroute', __name__)


@vacinaroute.route('/')
def index():
    return render_template('index.html')


@vacinaroute.route('/vacina/')
def vacina():
    vacinas = Vacina.query.all()
    return render_template('vacina/vacina_lista.html', titulo="Vacinas", vacinas=vacinas)


@vacinaroute.route('/vacina/novo/')
def vacina_novo():
    return render_template("vacina/vacina_novo.html", titulo="Nova Vacina")


@vacinaroute.route('/vacina/criar', methods=['POST', ])
def vacina_criar():
    nome = request.form['nome']
    vacinaTest = VacinaTest(nome=nome)
    if vacinaTest.value:
        vacina = Vacina(nome=vacinaTest.text)
        db.session.add(vacina)
        db.session.commit()
        return redirect(url_for('vacinaroute.vacina'))
    else:
        flash(str(vacinaTest.text), 'alert-danger')
        return redirect(url_for('vacinaroute.vacina_novo'))


@vacinaroute.route('/vacina/editar/<id>')
def vacina_editar(id):
    vacina = Vacina.query.filter_by(id=id).first()
    return render_template('vacina/vacina_editar.html', vacina=vacina)


@vacinaroute.route('/vacina/atualizar/<id>', methods=['POST'])
def vacina_atualizar(id):
    nome = request.form['nome']
    vacina = Vacina.query.filter_by(id=id).first()
    vacina.nome = nome
    db.session.commit()
    return redirect(url_for("vacinaroute.vacina"))


@vacinaroute.route('/vacina/excluir/<int:id>', methods=['DELETE', 'GET'])
def vacina_excluir(id):
    vacina = Vacina.query.filter_by(id=id).first()
    db.session.delete(vacina)
    db.session.commit()
    return redirect(url_for('vacinaroute.vacina'))

templates/aplicacao/aplicacao_editar.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('aplicacaoroute.aplicacao_atualizar', id=aplicacao.id) }}" method="post" class="needs-validation" novalidate>
    <fieldset>
        <div class="form-group has-validation">
            <label for="vacina">Vacina aplicada:</label>
            <select id="vacina" name="vacina" class="form-select" required>
                <option></option>
                {%for vacina in vacinas%}
                <option value="{{vacina.id}}" {% if vacina.id==aplicacao.id_vacina %} selected {% endif %}>
                    {{vacina.nome}}</option>
                {%endfor%}
            </select>
            <div class="invalid-feedback">
                Insira uma vacina.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="vacinador">Quem irá aplicar?</label>
            <select name="vacinador" id="vacinador" class="form-select" required>
                <option></option>
                {% for vacinador in vacinadores %}
                <option value="{{vacinador.crm}}" {% if vacinador.crm==aplicacao.crm %} selected {% endif %}>
                    {{vacinador.nome}} | {{vacinador.crmtemplate}}</option>
                {% endfor %}
            </select>
            <div class="invalid-feedback">
                Insira um vacinador.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="vacinado"> Quem será vacinado?</label>
            <select name="vacinado" id="vacinado" class="form-select" required>
                <option></option>
                {% for vacinado in vacinados %}
                <option value="{{vacinado.cns}}" {% if vacinado.cns==aplicacao.cns %} selected {% endif %}>
                    {{vacinado.nome}} | {{vacinado.cpf}}</option>
                {% endfor %}
            </select>
            <div class="invalid-feedback">
                Insira um vacinado.
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-salvar">Salvar</button>
        <a class="btn btn-danger" href="{{url_for('aplicacaoroute.aplicacao')}}">Cancelar</a>
    </fieldset>
</form>
{% include "script.html"%}
{% endblock %}

templates/aplicacao/aplicacao_list.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('aplicacaoroute.aplicacao_filtro') }}" method="post" class="needs-validation" novalidate>
     <fieldset>
        <div class="form-group has-validation" style="display: flex; margin: 5px;">
            <label for="cpf"> Vacinado CPF: </label>
            <input type="text" id="cpf" name="cpf" class="form-control" required style="height: 40px;">
            <button type="submit" class="btn btn-primary btn-salvar" style="margin-left: 5px ">Buscar</button>
            <div class="invalid-feedback">
                Insira uma vacina.
            </div>
        </div>
    </fieldset>
</form>
<table class="table table-striped table-responsive table-bordered">
    <thead class="thead-default">
    <tr>
        <th>id</th>
        <th>Vacina</th>
        <th>Aplciador / CRM</th>
        <th>Vacinado / CPF</th>
        <th>Data de Aplicação</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for aplicacao in aplicacoes %}
    <tr>
        <td>{{ aplicacao.id }}</td>
        <td>{{ aplicacao.vacina.nome }}</td>
        <td>{{ aplicacao.vacinador.nome }} / {{aplicacao.crm}}</td>
        <td>{{ aplicacao.vacinado.nome }} / {{aplicacao.vacinado.cpf}}</td>
        <td>{{ aplicacao.data.strftime('%d/%m/%Y') }}</td>
        <td>
            <a href="{{ url_for('aplicacaoroute.aplicacao_editar', id = aplicacao.id) }}" class="btn btn-warning">editar</a>
            <a href="{{ url_for('aplicacaoroute.aplicacao_excluir', id = aplicacao.id) }}" class="btn btn-danger">excluir</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    <a href="{{url_for('aplicacaoroute.aplicacao_novo')}}" class="btn btn-primary">Cadastrar</a>
    <a href="{{url_for('vacinaroute.index')}}" class="btn btn-dark">Voltar</a>
{% endblock %}

templates/aplicacao/aplicacao_novo.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('aplicacaoroute.aplicacao_criar') }}" method="post" class="needs-validation" novalidate>
    <fieldset>
        <div class="form-group has-validation">
            <label for="vacina">Vacina aplicada:</label>
            <select id="vacina" name="vacina" class="form-select" required>
                <option></option>
                {%for vacina in vacinas%}
                <option value="{{vacina.id}}">{{vacina.nome}}</option>
                {%endfor%}
            </select>
            <div class="invalid-feedback">
                Insira uma vacina.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="vacinador">Quem irá aplicar?</label>
            <select name="vacinador" id="vacinador" class="form-select" required>
                <option></option>
                {% for vacinador in vacinadores %}
                <option value="{{vacinador.crm}}">{{vacinador.nome}} | {{vacinador.crmtemplate}}</option>
                {% endfor %}
            </select>
            <div class="invalid-feedback">
                Insira um vacinador.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="vacinado"> Quem será vacinado?</label>
            <select name="vacinado" id="vacinado" class="form-select" required>
                <option></option>
                {% for vacinado in vacinados %}
                <option value="{{vacinado.cns}}">{{vacinado.nome}} | {{vacinado.cpf}}</option>
                {% endfor %}
            </select>
            <div class="invalid-feedback">
                Insira um vacinado.
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-salvar">Salvar</button>
        <a class="btn btn-danger" href="{{url_for('aplicacaoroute.aplicacao')}}">Cancelar</a>
    </fieldset>
</form>
{% include "script.html"%}
{% endblock %}