models/vacinado.py
from extensions import db


class Vacinado(db.Model):
    cns = db.Column(db.String(15), primary_key=True)
    cpf = db.Column(db.String(12), nullable=False, unique=True)
    nome = db.Column(db.String(128), nullable=False)
    dtNascimento = db.Column(db.Date, nullable=False)
    comorbidade = db.Column(db.Boolean, nullable=False)
    qtdDose = db.Column(db.Integer, nullable=False)
    aplicacao = db.relationship('Aplicacao', backref='vacinado', cascade="all, delete", passive_deletes=False, lazy=True)

routes/vacinado_route.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash

from Test.vacinadoTest import VacinadoTest
from extensions import db
from models.vacinado import Vacinado

vacinadoroute = Blueprint('vacinadoroute', __name__)


@vacinadoroute.route('/vacinado')
def vacinado():
    lista = Vacinado.query.all()
    return render_template('vacinado/vacinado_lista.html', titulo='Vacinados', vacinados=lista)


@vacinadoroute.route('/vacinado/novo')
def vacinado_novo():
    return render_template('vacinado/vacinado_novo.html', titulo='Novo Vacinado')


@vacinadoroute.route('/criarVacinado', methods=['POST', ])
def vacinado_criar():
    nome = request.form['nome']
    cpf = request.form['cpf']
    cns = request.form['cns']
    dtnascimento = datetime.strptime(request.form['nascimento'], '%Y-%m-%d').date()
    comorbidade = eval(request.form['comorbidade'])
    qtdDose = int(0)

    vacinadoTest = VacinadoTest(nome=nome, cpf=cpf, cns=cns, dtnascimento=dtnascimento, comorbidade=comorbidade,
                                qtdDose=qtdDose)

    if vacinadoTest.value:
        db.session.add(vacinadoTest.vacinado)
        db.session.commit()
        return redirect(url_for('vacinadoroute.vacinado'))
    else:
        flash(vacinadoTest.vacinado, 'alert-danger')
        return redirect(url_for('vacinadoroute.vacinado_novo'))


@vacinadoroute.route('/vacinado/atualizar/<string:cns>', methods=['POST', ])
def vacinado_atualizar(cns):
    vacinado = Vacinado.query.filter_by(cns=cns).first()
    if vacinado:
        vacinado.nome = request.form['nome']
        vacinado.cpf = request.form['cpf']
        vacinado.dtnascimento = datetime.strptime(request.form['nascimento'], '%Y-%m-%d').date()
        vacinado.comorbidade = eval(request.form['comorbidade'])
        vacinado.qtdDose = int(vacinado.qtdDose)
        db.session.commit()
    return redirect(url_for('vacinadoroute.vacinado'))


@vacinadoroute.route('/vacinado/editar/<string:cns>')
def vacinado_editar(cns):
    vacinado = Vacinado.query.filter_by(cns=cns).first()
    return render_template('vacinado/vacinado_editar.html', titulo='Editando Vacinado', vacinado=vacinado)


@vacinadoroute.route('/excluir/<string:cns>')
def vacinado_excluir(cns):
    try:
        vacinado = Vacinado.query.filter_by(cns=cns).first()
        db.session.delete(vacinado)
        db.session.commit()
        flash(f'O  Vacinado {cns} foi deletado com sucesso!', 'alert-success')
    except KeyError as key:
        raise ValueError(key)

    return redirect(url_for('vacinadoroute.vacinado'))

routes/vacinaroute.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from Test.vacinaTest import VacinaTest
from extensions import db
from models.vacina import Vacina

vacinaroute = Blueprint('vacinaroute', __name__)


@vacinaroute.route('/')
def index():
    return render_template('index.html')


@vacinaroute.route('/vacina/')
def vacina():
    vacinas = Vacina.query.all()
    return render_template('vacina/vacina_lista.html', titulo="Vacinas", vacinas=vacinas)


@vacinaroute.route('/vacina/novo/')
def vacina_novo():
    return render_template("vacina/vacina_novo.html", titulo="Nova Vacina")


@vacinaroute.route('/vacina/criar', methods=['POST', ])
def vacina_criar():
    nome = request.form['nome']
    vacinaTest = VacinaTest(nome=nome)
    if vacinaTest.value:
        vacina = Vacina(nome=vacinaTest.text)
        db.session.add(vacina)
        db.session.commit()
        return redirect(url_for('vacinaroute.vacina'))
    else:
        flash(str(vacinaTest.text), 'alert-danger')
        return redirect(url_for('vacinaroute.vacina_novo'))


@vacinaroute.route('/vacina/editar/<id>')
def vacina_editar(id):
    vacina = Vacina.query.filter_by(id=id).first()
    return render_template('vacina/vacina_editar.html', vacina=vacina)


@vacinaroute.route('/vacina/atualizar/<id>', methods=['POST'])
def vacina_atualizar(id):
    nome = request.form['nome']
    vacina = Vacina.query.filter_by(id=id).first()
    vacina.nome = nome
    db.session.commit()
    return redirect(url_for("vacinaroute.vacina"))


@vacinaroute.route('/vacina/excluir/<int:id>', methods=['DELETE', 'GET'])
def vacina_excluir(id):
    vacina = Vacina.query.filter_by(id=id).first()
    db.session.delete(vacina)
    db.session.commit()
    return redirect(url_for('vacinaroute.vacina'))

templates/vacinado/vacinado_editar.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('vacinadoroute.vacinado_atualizar', cns=vacinado.cns) }}" method="post" class="needs-validation" novalidate>
    <fieldset>
        <div class="form-group has-validation">
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control" value="{{vacinado.nome}}" required>
            <div class="invalid-feedback">
                Insira um Nome.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="cpf">CPF</label>
            <input type="text" id="cpf" name="cpf" class="form-control" value="{{vacinado.cpf}}" required>
            <div class="invalid-feedback">
                Insira um CPF.
            </div>
        </div>
        <div class="form-group has-validation">
            <label for="nascimento">Data de Nascimento</label>
            <input type="date" id="nascimento" name="nascimento" class="form-control" value="{{vacinado.dtNascimento}}"
                required>
            <div class="invalid-feedback">
                Insira sua data de nascimento.
            </div>
        </div>
        <div class="form-group has-validation">
            <labe>Comorbidade:</labe>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" id="comorbidadeTrue" name="comorbidade" value="True" {% if
                    vacinado.comorbidade %} checked {% endif %} required>
                <label for="comorbidadeTrue">Sim</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" id="comorbidadeFalse" name="comorbidade" value="False" {%
                    if not vacinado.comorbidade %} checked {% endif %} required>
                <label for="comorbidadeFalse">Não</label>
            </div>
        </div>
        <div class="form-group">
            <label for="dose">Quantidade de Dose</label>
            <input type="number" id="dose" name="dose" class="form-control" value="{{vacinado.qtdDose}}" disabled>
        </div>
        <div>
            <button type="submit" class="btn btn-primary btn-salvar">Atualizar</button>
            <a href="{{url_for('vacinadoroute.vacinado')}}" class="btn btn-danger">Cancelar</a>
        </div>
    </fieldset>
</form>
{% include "script.html"%}
{% endblock %}

templates/vacinado/vacinado_lista.html
{% extends "templates.html" %}
{% block conteudo %}
<table class="table table-striped table-responsive table-bordered">
    <thead class="thead-default">
    <tr>
        <th>Nome</th>
        <th>Nascimento</th>
        <th>CPF</th>
        <th>CNS</th>
        <th>Comorbidade</th>
        <th>Quant. Doses</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for vacinado in vacinados %}
    <tr>
        <td>{{ vacinado.nome }}</td>
        <td>{{ vacinado.dtNascimento.strftime('%d/%m/%Y') }}</td>
        <td>{{ vacinado.cpf }}</td>
        <td>{{ vacinado.cns }}</td>
        <td>{{ 'Sim' if vacinado.comorbidade else 'Não' }}</td>
        <td>{{ vacinado.qtdDose }}</td>
        <td>
            <a href="{{ url_for('vacinadoroute.vacinado_editar', cns=vacinado.cns) }}" class="btn btn-warning">editar</a>
            <a href="{{ url_for('vacinadoroute.vacinado_excluir', cns=vacinado.cns) }}" class="btn btn-danger">excluir</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    <a href="{{url_for('vacinadoroute.vacinado_novo')}}" class="btn btn-primary">Cadastrar</a>
    <a href="{{url_for('vacinaroute.index')}}" class="btn btn-dark">Voltar</a>
{% endblock %}

templates/vacinado/vacinado_novo.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('vacinadoroute.vacinado_criar') }}" method="post" class="needs-validation" novalidate>
    <div class="form-group has-validation">
        <label for="nome">Nome</label>
        <input type="text" id="nome" name="nome" class="form-control" aria-describedby="inputGroupPrepend" required>
        <div class="invalid-feedback">
            Insira um Nome.
        </div>
    </div>
    <div class="form-group has-validation">
        <label for="cpf">CPF</label>
        <input type="text" id="cpf" name="cpf" class="form-control" required>
        <div class="invalid-feedback">
            Insira um CPF.
        </div>
    </div>
    <div class="form-group has-validation">
        <label for="cns">CNS</label>
        <input type="text" id="cns" name="cns" class="form-control" required>
        <div class="invalid-feedback">
            Insira um CNS.
        </div>
    </div>
    <div class="form-group has-validation">
        <label for="nascimento">Data de Nascimento</label>
        <input type="date" id="nascimento" name="nascimento" class="form-control" required>
        <div class="invalid-feedback">
            Insira sua data de nascimento.
        </div>
    </div>
    <div class="form-group has-validation">
        <labe for="comorbidadeTrue">Comorbidade:</labe>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" id="comorbidadeTrue" name="comorbidade" value="True" required>
            <label for="comorbidadeTrue">Sim</label>
            <div class="invalid-feedback">
                Selecione uma das opções.
            </div>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" id="comorbidadeFalse" name="comorbidade" value="False"
                required>
            <label for="comorbidadeFalse">Não</label>
        </div>
    </div>

        <div>
            <button type="submit" class="btn btn-primary btn-salvar">Salvar</button>
            <a class="btn btn-danger" href="{{url_for('vacinadoroute.vacinado')}}">Cancelar</a>
        </div>
</form>
{% include "script.html"%}
{% endblock %}