models/vacina.py
from extensions import db


class Vacina(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(128))
    aplicacao = db.relationship('Aplicacao', backref='vacina', cascade="all, delete", passive_deletes=False, lazy=True)

routes/vacinaroute.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from Test.vacinaTest import VacinaTest
from extensions import db
from models.vacina import Vacina

vacinaroute = Blueprint('vacinaroute', __name__)


@vacinaroute.route('/')
def index():
    return render_template('index.html')


@vacinaroute.route('/vacina/')
def vacina():
    vacinas = Vacina.query.all()
    return render_template('vacina/vacina_lista.html', titulo="Vacinas", vacinas=vacinas)


@vacinaroute.route('/vacina/novo/')
def vacina_novo():
    return render_template("vacina/vacina_novo.html", titulo="Nova Vacina")


@vacinaroute.route('/vacina/criar', methods=['POST', ])
def vacina_criar():
    nome = request.form['nome']
    vacinaTest = VacinaTest(nome=nome)
    if vacinaTest.value:
        vacina = Vacina(nome=vacinaTest.text)
        db.session.add(vacina)
        db.session.commit()
        return redirect(url_for('vacinaroute.vacina'))
    else:
        flash(str(vacinaTest.text), 'alert-danger')
        return redirect(url_for('vacinaroute.vacina_novo'))


@vacinaroute.route('/vacina/editar/<id>')
def vacina_editar(id):
    vacina = Vacina.query.filter_by(id=id).first()
    return render_template('vacina/vacina_editar.html', vacina=vacina)


@vacinaroute.route('/vacina/atualizar/<id>', methods=['POST'])
def vacina_atualizar(id):
    nome = request.form['nome']
    vacina = Vacina.query.filter_by(id=id).first()
    vacina.nome = nome
    db.session.commit()
    return redirect(url_for("vacinaroute.vacina"))


@vacinaroute.route('/vacina/excluir/<int:id>', methods=['DELETE', 'GET'])
def vacina_excluir(id):
    vacina = Vacina.query.filter_by(id=id).first()
    db.session.delete(vacina)
    db.session.commit()
    return redirect(url_for('vacinaroute.vacina'))

templates/vacina/vacina_editar.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('vacinaroute.vacina_atualizar', id=vacina.id) }}" method="post" class="needs-validation" novalidate>
    <fieldset>
        <div class="form-group has-validation">
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control" value="{{vacina.nome}}" required>
            <div class="invalid-feedback">
                Insira uma vacina.
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-salvar">Salvar</button>
        <a class="btn btn-danger" href="{{url_for('vacinaroute.vacina')}}">Cancelar</a>
    </fieldset>
</form>
{% include "script.html"%}
{% endblock %}

templates/vacina/vacina_lista.html
{% extends "templates.html" %}
{% block conteudo %}
<table class="table table-striped table-responsive table-bordered">
    <thead class="thead-default">
    <tr>
        <th>id</th>
        <th>Nome</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for vacina in vacinas %}
    <tr>
        <td>{{ vacina.id }}</td>
        <td>{{ vacina.nome }}</td>
        <td>
            <a href="{{ url_for('vacinaroute.vacina_editar', id= vacina.id) }}" class="btn btn-warning">editar</a>
            <a href="{{ url_for('vacinaroute.vacina_excluir', id= vacina.id) }}" class="btn btn-danger">Excluir</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    <a href="{{url_for('vacinaroute.vacina_novo')}}" class="btn btn-primary">Cadastrar</a>
    <a href="{{url_for('vacinaroute.index')}}" class="btn btn-dark">Voltar</a>
{% endblock %}

templates/vacina/vacina_novo.html
{% extends "templates.html" %}
{% block conteudo %}
<form action="{{ url_for('vacinaroute.vacina_criar') }}" method="post" class="needs-validation" novalidate>
    <fieldset>
        <div class="form-group has-validation">
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control" required>
            <div class="invalid-feedback">
                Insira uma vacina.
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-salvar">Salvar</button>
        <a class="btn btn-danger" href="{{url_for('vacinaroute.vacina')}}">Cancelar</a>
    </fieldset>
</form>
{% include "script.html"%}
{% endblock %}